
#We dont want to use MSBuild
build: off

#Kick off the CI/CD pipeline
before_test: 
  - echo "started"
  - ps: install-module invokebuild
  - echo "installed"
  - ps: import-module invokebuild
  - echo "imported"
test_script:
  - ps: Invoke-Build -BuildNumber $Env:APPVEYOR_BUILD_NUMBER